### ISSUE TITLE
longer rss

### ISSUE THREAD

**Issue by UnSleep** [Joshkunz/tumblr2rss#1]
i follow a lot of blogs and i think that 20 articles is really very small size for Tumblr...

Can you upgrade it to 200 or more?

**Comment by Joshkunz** [comment]
The RSS feed is generated directly from the [tumblr API](https://www.tumblr.com/docs/en/api/v2), and by default they only return 20 results. You could fetch more results but you have to do the pagination stuff and submit multiple requests to the API. I didn't bother with it because my dashboard feed is low-activity and I never thought anyone else would use the thing.

I'll add it as an option but I definitely wouldn't make it the default. I'm not sure how tumblr does API rate-limiting and I don't want 10-requests per user per hour-or-so (whenever the feed fetcher checks) getting the app blacklisted by tumblr.

Unfortunately I won't have time to add it till the 16th at the soonest though.

**Comment by Joshkunz** [comment]
Ok the patch should be running on `rss.joshkunz.com`. Just add `?length=<count>` to the end of your feed URL where `<count>` is in the range 1-100 to get an RSS feed of that length from your tumblr dashboard. For example, `http://rss.joshkunz.com/dashboard/foo.rss?length=30`.

I decided on 100 as the max because I'm a little worried about getting rate-limited by tumblr and I don't want to worry about locally caching responses. The max limit is easy to change though, so let me know if you still don't think it's enough.
