### ISSUE TITLE
The callback address？

### ISSUE THREAD

**Issue by IMLR** [joshkunz/tumblr2rss#5]
Thank you very much for making such a good tool. I can use my RSS reader to read my tumblr following blog now.

After using it for a while, I found that the service you provided was updated about three hours, perhaps because I was following too many blogs and many posts were not pushed.

I try to build this service on my own server, but I have a problem in step 0: 
Tumblr requires a callback address and I don't know it.

On the other hand, I don't know where to set the frequency of updates?

Thank you for your creation and look forward to your answer.

**Comment by joshkunz** [comment]
Thanks, I'm glad you think it's useful :)

> After using it for a while, I found that the service you provided was updated about three hours, perhaps because I was following too many blogs and many posts were not pushed.

tumblr2rss is pretty dumb, it just calls the Tumblr API and renders it as an RSS feed. tumblr2rss does have the drawback that it will only render the last 20 items in the feed. If your scraper is only scraping every 3 hours, and there are more than 20 posts in that period of time, they will not be included in the feed. tumblr2rss does have an intentionally undocumented feature that allows you to include more posts.  You can try adding `?length=<count>` where `<count>` is a number <=100. Instead of the default, tumblr2rss will render that many posts in the feed.

> I try to build this service on my own server, but I have a problem in step 0: Tumblr requires a callback address and I don't know it.

The callback address is the URL of the page that tumblr redirects the user to after they have registered. It's part of the OAuth authentication flow. You can read more about it [here](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2). tumblr2rss uses the /registered path for this purpose. So if you were hosting the server on foo.com, you would use `http://foo.com/registered` as the callback address.

> On the other hand, I don't know where to set the frequency of updates?

The easiest way is to just increase the number of posts in the feed using `?length=...` as described earlier.

**Comment by IMLR** [comment]
I have tried it and it is very successful.
Thank you very much

**Comment by joshkunz** [comment]
Glad to hear it!
